// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mtjdvwimvnaswnufkciq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im10amR2d2ltdm5hc3dudWZrY2lxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4MjAzMzgsImV4cCI6MjA2NTM5NjMzOH0.HnfXRyNLDQrTWHb4LR7kUUqPd5Ix-wvVF1AmIpXMzB0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);